name: SkiTrails
options:
  bundleIdPrefix: com.skitrails
  deploymentTarget:
    iOS: 17.0
packages:
  MapboxMaps:
    url: https://github.com/mapbox/mapbox-maps-ios.git
    from: 10.16.0
  Sentry:
    url: https://github.com/getsentry/sentry-cocoa.git
    from: 8.17.1
  SkiTrailsCore:
    path: ./
targets:
  SkiTrailsCore:
    type: framework
    platform: iOS
    sources:
      - path: Sources/SkiTrailsCore
    dependencies:
      - package: MapboxMaps
        product: MapboxMaps
      - package: Sentry
        product: Sentry
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.skitrails.core
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0.0
  SkiTrails:
    type: application
    platform: iOS
    sources: 
      - path: App/SkiTrails
        includes:
          - "**/*.swift"
        excludes:
          - "Resources/Info.plist"
    dependencies:
      - target: SkiTrailsCore
      - package: MapboxMaps
        product: MapboxMaps
      - package: Sentry
        product: Sentry
    settings:
      base:
        INFOPLIST_FILE: App/SkiTrails/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.skitrails.app
        DEVELOPMENT_TEAM: ""  # Add your team ID here if you have one
    info:
      path: App/SkiTrails/Info.plist
      properties:
        CFBundleName: SkiTrails
        CFBundleDisplayName: Ski Trails
        CFBundlePackageType: APPL
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIRequiredDeviceCapabilities:
          - armv7